{% set name = "fpsample" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leonardodalinky/fpsample/archive/v{{ version }}.tar.gz
  sha256: 0df8335a7b6b7da5e9cf6b43fa652813b5fbf4253663a9aa2476b2e19e7de5bb

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - make  # [unix]
    - pip
    - python
    - scikit-build-core >=0.11
  host:
    - pip
    - python
    - scikit-build-core >=0.11
    - pybind11 >=2.10
    - numpy
    - cmake  # [win]
  run:
    - numpy >=1.16.0
    - python
    - pybind11 >=2.10

test:
  imports:
    - fpsample
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leonardodalinky/fpsample
  summary: Python efficient farthest point sampling (FPS) library
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
