{% set name = "fpsample" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leonardodalinky/fpsample/archive/v{{ version }}.tar.gz
  sha256: 2080072542064965d97bb5e1bf283b95e1181ba13dc2a14fbdcea8a691904bc8

build:
  number: 0
  script:
    - cd $SRC_DIR && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml  # [unix]
    - cd %SRC_DIR% && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - pip
    - python
    - maturin >=1.2.0,<2
  host:
    - pip
    - python
    - maturin >=1.2.0,<2
  run:
    - numpy >=1.16.0
    - python

test:
  imports:
    - fpsample
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leonardodalinky/fpsample
  summary: Python efficient farthest point sampling (FPS) library
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
