{% set name = "fpsample" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leonardodalinky/fpsample/archive/v{{ version }}.tar.gz
  sha256: 2080072542064965d97bb5e1bf283b95e1181ba13dc2a14fbdcea8a691904bc8

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [unix]
    - make  # [unix]
    - pip
    - python
    - scikit-build-core >=0.11
  host:
    - pip
    - python
    - scikit-build-core >=0.11
    - pybind11 >=2.6
    - numpy
  run:
    - numpy >=1.16.0
    - python
    - pybind11 >=2.6

test:
  imports:
    - fpsample
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leonardodalinky/fpsample
  summary: Python efficient farthest point sampling (FPS) library
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
